export type Category =
  | "Neuroscience"
  | "Mental Health"
  | "Mindfulness"
  | "Research"
  | "Interview";

export interface Episode {
  id: string;
  title: string;
  guest: string;
  date: string;
  duration: string;
  category: Category;
  cover: string;
  accent: string;
  short: string;
  paragraphs: [string, string, string];
  links: {
    youtube: string;
    spotify: string;
    amazon: string;
    apple: string;
  };
}

const links = {
  youtube: "https://music.youtube.com",
  spotify: "https://open.spotify.com",
  amazon: "https://music.amazon.com",
  apple: "https://podcasts.apple.com",
};

export const episodes: Episode[] = [
  {
    id: "ep-01",
    title: "The Plastic Brain: Rewiring Habits at Any Age",
    guest: "Dr. Anika Rao",
    date: "May 28, 2026",
    duration: "52 min",
    category: "Neuroscience",
    cover:
      "https://images.unsplash.com/photo-1559757175-08d4f8d4f5b5?auto=format&fit=crop&w=1200&q=80",
    accent: "from-indigo-500/40 via-purple-500/30 to-fuchsia-500/40",
    short:
      "Why your brain keeps changing — and how to use that to your advantage.",
    paragraphs: [
      "Neuroplasticity has become one of the most misused words in pop science, but its core idea is genuinely radical: the brain you wake up with tomorrow is not the brain you went to sleep with tonight. Dr. Anika Rao opens the conversation by walking through the cellular machinery of synaptic change — long-term potentiation, dendritic spine remodeling, and the surprising role of sleep in pruning what the day failed to use.",
      "From there, the discussion moves into the messy, lived experience of trying to change a habit. Anika argues that most self-help frameworks ignore the metabolic cost of rewiring. New circuits are expensive, and the brain treats them like a startup project: it needs evidence the investment will pay off. We talk about how repetition, emotional salience, and small wins act like seed funding for a habit, and why a single missed day is rarely the real reason people fall off.",
      "The episode closes with a practical toolkit: protocols for attention training, why journaling beats willpower, and the underrated importance of boredom in consolidating new behaviors. If you've ever wondered whether you're 'too old' to change, this conversation is a quiet, evidence-backed argument that you almost certainly aren't.",
    ],
    links,
  },
  {
    id: "ep-02",
    title: "Anxiety Is Information: Listening to the Signal",
    guest: "Dr. Marcus Wei",
    date: "May 14, 2026",
    duration: "47 min",
    category: "Mental Health",
    cover:
      "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=80",
    accent: "from-amber-400/40 via-rose-400/30 to-pink-500/40",
    short:
      "Reframing anxiety from enemy to early-warning system you can actually read.",
    paragraphs: [
      "We tend to talk about anxiety the way we talk about weather — as something that happens to us. Dr. Marcus Wei pushes back on that framing in this episode, treating anxiety instead as a structured, interpretable signal generated by a prediction machine that thinks it's protecting you. The conversation begins with the predictive-processing view of emotion and why your nervous system is, at all times, betting on the future.",
      "Marcus then unpacks the difference between productive anxiety, which sharpens attention and prepares action, and the runaway loops that fuel disorders. He shares clinical examples of patients who learned to 'read' their anxiety the way a sailor reads wind — not by suppressing it, but by asking what it was tracking and whether the model behind it was still accurate.",
      "The final third of the episode is about practice. We cover interoceptive exposure, the under-discussed role of breath rhythm in vagal tone, and why community is a more powerful regulator than any single technique. Listeners leave with a vocabulary for talking to their own anxiety instead of fighting it.",
    ],
    links,
  },
  {
    id: "ep-03",
    title: "The Default Mode: What Your Brain Does When You Don't",
    guest: "Dr. Priya Iyer",
    date: "April 30, 2026",
    duration: "61 min",
    category: "Research",
    cover:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    accent: "from-cyan-400/40 via-sky-500/30 to-blue-600/40",
    short:
      "The hidden network behind daydreaming, identity, and creative leaps.",
    paragraphs: [
      "When you stop doing anything in particular, your brain does not switch off — it switches modes. The Default Mode Network (DMN) lights up the moment your task ends, and Dr. Priya Iyer has spent fifteen years mapping what it's actually doing in there. This episode is a deep tour through the network that builds your sense of self.",
      "Priya describes the DMN as the brain's autobiographer: it stitches memories into narrative, simulates futures, and rehearses social scenarios. We discuss why a quiet, well-fed DMN seems to correlate with creative insight, and why a noisy, ruminative one is implicated in depression. The science here is genuinely surprising — including evidence that some of the most important cognitive work happens precisely when we feel least productive.",
      "The episode ends on an applied note: how to deliberately give your DMN room to operate. We cover walking without a podcast in your ear (sorry), the case for unstructured weekends, and the difference between rest that restores and rest that just numbs. A good listen for anyone who feels guilty about staring out a window.",
    ],
    links,
  },
  {
    id: "ep-04",
    title: "Meditation, Measured: What FMRI Tells Us About Stillness",
    guest: "Sister Elena Cho",
    date: "April 16, 2026",
    duration: "55 min",
    category: "Mindfulness",
    cover:
      "https://images.unsplash.com/photo-1545389336-cf090694435e?auto=format&fit=crop&w=1200&q=80",
    accent: "from-emerald-400/40 via-teal-500/30 to-cyan-500/40",
    short:
      "A contemplative and a neuroscientist meet over thirty years of brain scans.",
    paragraphs: [
      "Sister Elena Cho is unusual: a contemplative who spent two decades inside an MRI scanner as part of long-running studies on meditation. In this episode, she walks through what those scans actually showed — and, more interestingly, what they didn't. The picture is more nuanced than the wellness industry tends to admit.",
      "We talk about the measurable changes: thicker insula, calmer amygdala response to stressors, more efficient attention networks. But Elena is careful to separate the headline effects from the lived ones. Some of the most profound shifts she describes — equanimity, a softening of self-reference — show up in behavior long before they show up cleanly on a scan.",
      "The conversation turns practical in the second half: what kind of practice produces what kind of change, why ten minutes a day really does seem to be a meaningful threshold, and how to tell the difference between genuine progress and spiritual bypass. Elena's voice is calm and unhurried — the episode itself feels like a small practice.",
    ],
    links,
  },
  {
    id: "ep-05",
    title: "Sleep Is Not Optional: The Glymphatic Story",
    guest: "Dr. Jonas Ferreira",
    date: "April 02, 2026",
    duration: "49 min",
    category: "Research",
    cover:
      "https://images.unsplash.com/photo-1531353826977-0941b4779a1c?auto=format&fit=crop&w=1200&q=80",
    accent: "from-violet-500/40 via-indigo-500/30 to-blue-500/40",
    short:
      "Why your brain literally washes itself, and what happens when it can't.",
    paragraphs: [
      "Until about fifteen years ago, the brain's waste-clearance system was a mystery. Then the glymphatic system was described, and a generation of sleep researchers had a new villain to chase. Dr. Jonas Ferreira is one of them, and this episode is a clear-eyed tour through what we now know about the brain's nightly cleaning crew.",
      "Jonas explains how cerebrospinal fluid moves through the brain during deep sleep, flushing out metabolic byproducts including the proteins implicated in Alzheimer's disease. The mechanism is elegant, and the implications are sobering: chronic short sleep isn't just tiring, it's a slow-motion cleaning strike against your own neurons.",
      "We close with the boring, important stuff that actually moves the needle: light exposure timing, why alcohol fragments deep sleep even when you don't notice, and the surprisingly large effect size of a consistent wake time. The episode makes a quietly compelling case that sleep hygiene is the highest-leverage neurological intervention most people will ever have access to.",
    ],
    links,
  },
  {
    id: "ep-06",
    title: "Memory Is a Reconstruction, Not a Recording",
    guest: "Dr. Lina Okafor",
    date: "March 19, 2026",
    duration: "44 min",
    category: "Interview",
    cover:
      "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=1200&q=80",
    accent: "from-orange-400/40 via-red-400/30 to-rose-500/40",
    short:
      "Every time you remember something, you change it. Here's why that's mostly fine.",
    paragraphs: [
      "Memory feels like playback. It is not. Dr. Lina Okafor opens this episode by dismantling the recording metaphor and replacing it with something more honest: every act of remembering is also an act of editing. The brain is not retrieving a file, it's rebuilding the experience from fragments scattered across cortex and hippocampus.",
      "Lina walks through the elegant, unsettling research on memory reconsolidation — the window of plasticity that opens each time a memory is recalled. We discuss eyewitness testimony, why family stories drift in predictable directions, and the therapeutic possibilities of editing traumatic memories during the reconsolidation window without erasing the underlying facts.",
      "The episode lands on a generous note. If memory is reconstructive, then the past is, in a real sense, negotiable — not in what happened, but in what it now means. Lina argues this is one of the most underused tools in human psychology: the deliberate, careful re-narration of old experiences in the light of new understanding.",
    ],
    links,
  },
];

export const categories: Category[] = [
  "Neuroscience",
  "Mental Health",
  "Mindfulness",
  "Research",
  "Interview",
];
